development:
  adapter: postgresql
  database: rodauth_demo_development

test:
  adapter: postgresql
  database: rodauth_demo_test

production:
  adapter: postgresql
  database: rodauth_demo_production
